INSERT INTO HUMAN (HUMAN_ID, FIO) VALUES (1, 'Булгаков Михаил Афанасьевич');
INSERT INTO HUMAN (HUMAN_ID, FIO) VALUES (2, 'Достоевский Федор Михайлович');
INSERT INTO HUMAN (HUMAN_ID, FIO) VALUES (3, 'Замятин Евгений Иванович');

INSERT INTO DOCUMENT (DOCUMENT_ID, HUMAN_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, IS_STATUS_ACTIVE)
VALUES (1, 1, 123456, 'PASSPORT', true);
INSERT INTO DOCUMENT (DOCUMENT_ID, HUMAN_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, IS_STATUS_ACTIVE)
VALUES (2, 2, 777456, 'PASSPORT', true);
INSERT INTO DOCUMENT (DOCUMENT_ID, HUMAN_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, IS_STATUS_ACTIVE)
VALUES (3, 1, 852777, 'MEDICINE_PASSPORT', true);
INSERT INTO DOCUMENT (DOCUMENT_ID, HUMAN_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, IS_STATUS_ACTIVE)
VALUES (4, 3, 852767, 'INN', true);
INSERT INTO DOCUMENT (DOCUMENT_ID, HUMAN_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, IS_STATUS_ACTIVE)
VALUES (5, 3, 877767, 'PASSPORT', false);
